### ISSUE TITLE
regarding the export option

### ISSUE THREAD

**Issue by kr230601** [Amalg016/PixelEditor#1]
**Is your feature request related to a problem? Please describe.**
The export option is on the toolbar, which is kind of annoying.

**Describe the solution you'd like**
I would like another window for exporting.

**Describe alternatives you've considered**
like, use another floating window like the toolbar currently used?

**Comment by Amalg016** [comment]
yeah, totally forget about that one.Thanks for pointing it out. I will add that one also like a floating window.

**Comment by Amalg016** [comment]
closes #1

**Comment by Amalg016** [comment]
closes #1

**Comment by Amalg016** [comment]
added it 1337e2e50bb1b790bf5f88004e9ae1ba7c29aafc

**Comment by Amalg016** [comment]
added it in 1337e2e50bb1b790bf5f88004e9ae1ba7c29aafc
